### ISSUE TITLE
encrypted:k8s!n substitution not working for patch-s3.yml

### ISSUE THREAD

**Issue by andrijaperovic** [armory/spinnaker-kustomize-patches#53]
Trying to patch my SpinnakerService using s3 patch configuration, if I provide the values in plaintext the kustomization works as expected, however when leveraging `encrypted:k8s!n` variable substitution with k8s secret `spin-secrets` , it seems the variable substitution is not happening correctly as I get 403 exceptions in front50.

Any idea if there is a list which indicates what fields in SpinnakerService support substitution and which do not? I did not see anything at https://docs.armory.io/docs/armory-admin/secrets/secrets-kubernetes/.

Here is my s3 patch file for reference:

```
apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:
    config:
      persistentStorage:
        persistentStoreType: s3
        s3:
          bucket: encrypted:k8s!n:spin-secrets!k:aws-s3-bucket-name         # The name of an S3 bucket that Spinnaker will use to save information like applications and pipelines. Must be globally unique.
          rootFolder: front50                                               # The root folder in the chosen bucket to place all of Spinnaker's persistent data in.
          region: encrypted:k8s!n:spin-secrets!k:aws-s3-bucket-region       # (Optional). Used when Spinnaker creates the S3 bucket automatically.
          accessKeyId: encrypted:k8s!n:spin-secrets!k:aws-access-key        # (Optional). Your AWS Access Key ID. If not provided, Operator/Spinnaker will try to find AWS credentials as described at http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html#credentials-default
          secretAccessKey: encrypted:k8s!n:spin-secrets!k:aws-secret-key    # (Secret, Optional). Your AWS Secret Key.

```
